### ISSUE TITLE
More lighting issues

### ISSUE THREAD

**Issue by jamesjimmy88** [Frinn38/Custom-Machinery#40] opened 2022-04-18 07:39 UTC
There appears to be some sort of weird offset in the calculations of the blocks' lighting.
https://streamable.com/y8iieh

As shown in the video, there's no issue when the block is facing north.
For the test I used `"appearance": {"block": "minecraft:furnace[lit=true]"}`, but there's no difference with custom models.

Tested on CM 0.5.7, Openloader 9.0.3 and no other mods on Forge 36.2.33

**Comment by Frinn38** [comment] 2022-04-26 13:56
Sorry for not replying sooner, that look very weird indeed.
The problem is that I can't reproduce this... The machine shouldn't have ambient occlusion enable on itself (which mean no shadow should appear).
Do you have optifine installed, or some resourcepack or shaders or anything that can mess with rendering ?

**Comment by jamesjimmy88** [comment] 2022-04-28 19:06
Welp, I re-made an instance with the same settings and I can't reproduce it anymore.
I'm sure that I wasn't using anything but Openloader and CM (at the time I made a separate instance just to isolate this issue for the video).
I'll let you know if I stumble upon this issue again in the future.

**Comment by Frinn38** [comment] 2022-04-28 20:48
¯\_(ツ)_/¯
Maybe your instance was somehow corrupted or using an older version of CM :/
Anyway if it work now that's great ^^ I will close this issue for now, if you encounter this bug again leave a comment and I will reopen it.

**Closed as completed by Frinn38** 2022-04-28 20:48 UTC
Labels: bug, help wanted
