### ISSUE TITLE
Can't produce fluids if the tank already has some

### ISSUE THREAD

**Issue by jamesjimmy88** [Frinn38/Custom-Machinery#23] opened 2021-08-06 13:58 UTC
Recipes that generate fluids don't work if the output tank has any fluid in it, even if the fluid in the tank is the same as the one that would be generated.
Tested with Custom Machinery Ver. 0.4.4 on Forge 36.2.2

**Comment by Frinn38** [comment] 2021-08-06 16:36
I can't reproduce this, I just pushed an update (0.4.5) that changes some things on that end. If it still not work after updating send me your machine json with a recipe that don't work.

**Comment by jamesjimmy88** [comment] 2021-08-06 20:28
Still not working on 0.4.5 - here's the scripts
Machine json https://pastebin.com/5j9zH34T
Recipe json: https://pastebin.com/fBc66baX

Also the guis are apparently broken in the new update - the game screen dims like with any other inventory, but nothing is shown except for JEI on the right. Reverting to 0.4.4 fixes it

**Comment by jamesjimmy88** [comment] 2021-08-07 07:58
Disregard the part about GUIs not working; I was using the same world and the machines reverted to dummy blocks. The main issue with fluids still stands.

**Comment by Frinn38** [comment] 2021-08-12 18:51
Fixed in 0.4.6

**Closed as completed by Frinn38** 2021-08-12 18:51 UTC
