### ISSUE TITLE
Redstone requirement breaks recipes

### ISSUE THREAD

**Issue by Faeranne** [Frinn38/Custom-Machinery#27] opened 2021-08-07 20:10 UTC
Adding a redstone component to the requirements causes the recipe to constantly run regardless of any input.

**Comment by Frinn38** [comment] 2021-08-12 18:53
Can't reproduce this, in the 0.4.6 update I changed a bit how redstone requirement/component works, if this is still not fixed in 0.4.6 please send me a recipe and machine json that have this issue.

**Comment by Frinn38** [comment] 2021-08-22 19:22
I guess it's fixed, if not you can reopen the issue.

**Closed as completed by Frinn38** 2021-08-22 19:22 UTC
